### PR TITLE
Return size of the queue in ProcessInfo.

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by hyperthunk** [comment]
Looks good. Why don't we change the type of queueSize so it's no longer in `Maybe` as we're always able to calculate that now?

**Comment by qnikst** [comment]
Reasonable, I have tried to not break API at all. But I can change to of cause.

**Comment by hyperthunk** [comment]
Yes, let's break it.

**Comment by qnikst** [comment]
Updated

**Pull request merged**
