### PR TITLE
- make it compile with lts-20.12

### PR DESCRIPTION
**Pull request by ldobrek**

### CODE REVIEW

**Comment by davidsd** [comment]
I just ran CI, and there was a failure in the 9.2.6 test:

    Error: While constructing the build plan, the following exceptions were encountered:

    In the dependencies for distributed-static-0.3.9:
        bytestring-0.11.4.0 from stack configuration does not match >=0.10 && <0.11  (latest matching
                            version is 0.10.12.1)
    needed due to distributed-process-tests-0.4.11 -> distributed-static-0.3.9

    Some different approaches to resolving this:
    
      * Set 'allow-newer: true'
        in /__w/distributed-process/distributed-process/stack-root/config.yaml to ignore all version constraints and build anyway.
    
      * Recommended action: try adding the following to your extra-deps
        in /__w/distributed-process/distributed-process/stack-ghc-9.2.6.yaml:

    - bytestring-0.10.12.1@sha256:82dba4c2de4fdd8b419ed28aec2c14cfe4a3f43d1d6e2263ab26962e7398048e,6254

    Plan construction failed.

**Comment by davidsd** [comment]
It looks like the latest version of distributed-static on github allows for newer `bytestring` (https://github.com/haskell-distributed/distributed-static/commit/696f6094763cd51e7c719436444b7233f0eb09f4), but that change may not be incorporated on stackage.

**Comment by ldobrek** [comment]
> I just ran CI, and there was a failure in the 9.2.6 test:
Thank you

I relaxed the bound but frankly not sure this will fix it as I don't really understand why it builds on my box. I am sorry if it will take a few iterations.

**Comment by davidsd** [comment]
The tests are still failing. I think the problem is that the version of `distributed-static` on hackage is not compatible with the latest ByteString which is in lts-20.12. Perhaps you could edit the stack.yaml to point to the latest git commit for `distributed-static` (`03604c7db49fd74a925cba19fe97d5c9f97d8eb4`) instead of using the version on hackage.

**Comment by Bodigrim** [comment]
@davidsd `distributed-static` should no longer be a problem, it allows `bytestring-0.11` now. Could you please rerun CI?

**Comment by davidsd** [comment]
@Bodigrim Thanks for your hackage revisions to `distributed-static` and `network-transport-inmemory`! With them, I managed to get this working with ghc-9.2.7. Thanks, @ldobrek for kicking this off!

**Comment by Bodigrim** [comment]
@ldobrek could we please have a new release of `distributed-process`? The latest one is woefully obsolete.

**Comment by Bodigrim** [comment]
@davidsd could we please have a new release of `distributed-process`? The latest one is woefully obsolete.

**Comment by davidsd** [comment]
I’m not sure I have permissions to upload to hackage. I’ll try to talk to the longer term maintainers.

**Comment by Bodigrim** [comment]
Looking at https://hackage.haskell.org/package/distributed-process/maintainers/, you probably don't.

**Comment by davidsd** [comment]
@facundominguez @hyperthunk I am willing to make a new release for `distributed-process` and upload it to hackage. But I do not currently have permissions to do so. (I've also never maintained a package on hackage, so I'm not sure whether you want to just hand that responsibility over to me.) How would you like to proceed?

**Comment by hyperthunk** [comment]
@facundominguez how do we feel about extending maintainer rights? I personally have not had time to commit to the project for some years now and feel it would be good for it to get a new lease of life...

**Comment by facundominguez** [comment]
> @facundominguez how do we feel about extending maintainer rights?

👍 Sounds good to me.

**Comment by Bodigrim** [comment]
@facundominguez @hyperthunk @davidsd any progress with extending maintainer rights? It would be lovely to have a new release of `distributed-process` on Hackage.

**Comment by facundominguez** [comment]
I went ahead and added David to the maintainers of distributed-process in hackage. Thanks @davidsd!

**Comment by davidsd** [comment]
Thanks @facundominguez! I'm wondering if I could also be added to the maintainer list for the following packages, since they're all interrelated:

https://hackage.haskell.org/package/rank1dynamic
https://hackage.haskell.org/package/distributed-static
https://hackage.haskell.org/package/distributed-process-async
https://hackage.haskell.org/package/network-transport
https://hackage.haskell.org/package/network-transport-tcp
https://hackage.haskell.org/package/network-transport-tests

Also, would you be willing to add @joelmccracken as well? He recently helped update the CI infrastructure for some of these packages, and I'd appreciate having his help with maintenance.

**Comment by facundominguez** [comment]
> I'm wondering if I could also be added to the maintainer list for the following packages

Done.

> Also, would you be willing to add @joelmccracken as well? 

I'll leave this to you, as you should be able to edit the list of maintainers now.

**Comment by Bodigrim** [comment]
@davidsd any chance to make a Hackage release of `distributed-process` please?

**Comment by joelmccracken** [comment]
Hi! I recently found out that I was indeed given permission to publish new
distributed-process versions. I will see about doing it this week.

I have never actually released a package on hackage, so this is new to me,
so I'll be going slowly so that I don't mess it up.

(specifically, I want to try publishing a prerelase package)

**Pull request merged**
