### PR TITLE
Move CI to travis containers and build with ghc 7.10.2.

### PR DESCRIPTION
**Pull request by facundominguez**

### CODE REVIEW

**Comment by facundominguez** [comment]
cc @mboes

**Comment by facundominguez** [comment]
binutils-dev is not installed, don't know why yet. Anyone knows what is that needed for? It was in the former .yml file?

**Comment by mboes** [comment]
Do we need binutils-dev? Maybe we don't anymore. Don't know why it was there to begin with.

:+1:

**Comment by qnikst** [comment]
LGTM

**Pull request merged**
