### PR TITLE
Monorepo structure and cleanup

### LINKED ISSUE #382: Meta: merging most `haskell-distributed` repos into one
Dear @haskell-distributed/maintainers,

I would like to streamline maintenance of packages in this organization by merging most repositories into one. This will help keep all dependencies up-to-date, run cross-cutting tests, etc.

`cabal` has great support for multiple packages per repository; I have been working on Haskell monorepos for a few years and I love it.

Any thoughts or objections?

### PR DESCRIPTION
**Pull request by LaurentRDC**
This is a pull request that reforms the `distributed-process` repository into a monorepo, containing most relevant packages in the `haskell-distributed organization`.

See #382 for discussion 

List of merged packages:
* [x] distributed-process-async
* [x] distributed-process-client-server
* [x] distributed-process-execution
* [x] distributed-process-extras
* [x] distributed-process-simplelocalnet
* [x] distributed-process-supervisor
* [x] distributed-process-systest 
* [x] distributed-static
* [x] network-transport
* [x] network-transport-inmemory
* [x] network-transport-tcp
* [x] network-transport-tests 
* [x] rank1dynamic

Other repositories merged:
* [x] haskell-distributed.github.com

This PR also includes some cleanup, including:
* Harmonizing the dependency versions of all packages in the repo, such that all packages can be build using GHC 8.10 up to GHC 9.10
* Dropping support for GHC before 8.10, and simplifying all the CPP cruft
* Cleaning up all cabal files;
* Added an explicit `CONTRIBUTING.md` file.
* Continuous testing on Ubuntu

TODO after merge: 
* Deploy the website in the `website/` directory, rather than the `haskell-distributed.github.com` repo
* Update the links to this repo for all affected packages on Hackage
* Archive the merged repositories

### CODE REVIEW

**Comment by LaurentRDC** [comment]
Procedure I am using to maintain commit histories:

1. For some repo `some-repo`, create branch `monorepo-structure`;
2. In repo `some-repo`, move the relevant files under `packages/some-repo/*`
3. In the `distributed-process` repo, run:
```bash
git remote add some-repo https://github.com/haskell-distributed/some-repo -f
git pull some-repo monorepo-structure --allow-unrelated-histories
```

This will merge `some-repo` into `distributed-process` while keeping commit histories.

**Comment by LaurentRDC** [comment]
@davidsd This pull request is huge, so I can't expect anyone to actually review it.

Would you confirm to me that your workflow still works though? Can you build e.g. `distributed-process`?

I think you use Slack but I don't, so I'm not sure whether things still work.

**Review by davidsd — APPROVED** [review]
After adding an `extra-deps` field for `rematch` in the stack.yaml files, I was able to build everything. It looks good to me!

**Comment by davidsd** [comment]
I'm not sure what's going on with the one failing test.

**Comment by LaurentRDC** [comment]
Some of the tests are quite flaky. There's an option to rerun failed runs on Github actions, which I had to use a lot

**Comment by davidsd** [comment]
Regarding renaming this repo, I vote against. I think the name "distributed-process" makes sense, since it is the name of the "main" package here, and also the prefix of several other packages here. These are the names people will see on hackage when they search for this functionality -- they will likely not know what "cloud haskell" is unless they read some of the literature from around when cloud haskell was born.

**Comment by LaurentRDC** [comment]
Makes sense, no name changes

**Comment by LaurentRDC** [comment]
In the end, the website must be published from a special repo with the organization name for it to be published at `haskell-distributed.github.io`.

**Comment by joelmccracken** [comment]
I see you're building a bikeshed and deciding on the color! May I just comment that I've noticed some confusion around the difference between "cloud haskell" and "distributed process", and I suspect that renaming back may somehow cause additional confusion?

**Comment by LaurentRDC** [comment]
@joelmccracken Do not worry, I will not rename this organization. 

To address potential confusion about Cloud Haskell / distributed-process, I have created an organization README: https://github.com/haskell-distributed/.github/blob/main/profile/README.md

**Comment by joelmccracken** [comment]
> @joelmccracken Do not worry, I will not rename this repository.
> 
> To address potential confusion about Cloud Haskell / distributed-process, I have created an organization README: https://github.com/haskell-distributed/.github/blob/main/profile/README.md

Beautiful, thank you!

**Pull request merged**
