### PR TITLE
Use inmemory and tcp backend in CI

### PR DESCRIPTION
**Pull request by qnikst**
This patch depends on https://github.com/haskell-distributed/distributed-process-tests/pull/19

### CODE REVIEW

**Comment by facundominguez** [comment]
I can't see any tests executed in the travis logs.

**Comment by qnikst** [comment]
This error is intended unless we merge PR mentioned above.

**Comment by facundominguez** [comment]
PR #19 was merged. This PR still fails CI. But I'm not sure the failure is related.

**Comment by qnikst** [comment]
Seems related, will check that later

**Comment by qnikst** [comment]
Seems that inmemory tests healed, can we merge this?

**Comment by facundominguez** [comment]
I still can't see tests run in the travis output.

**Comment by qnikst** [comment]
I have no idea how to show results while performing cabal install --run-tests, but have you seen build test runtime errors  before things got fixed in d-p-tests?

**Comment by facundominguez** [comment]
LGTM

**Comment by facundominguez** [comment]
@qnikst, fix conflicts?

**Comment by facundominguez** [comment]
Done under tag v0.6.0.

**Pull request closed without merging**
