### PR TITLE
Adapt to GHC 8.0 interface changes

### PR DESCRIPTION
**Pull request by bgamari**
* `mkWeak#` now expects a raw state transformer instead of a boxed `IO` action.
 * the `template-haskell` `VarI` constructor has lost a field

### CODE REVIEW

**Comment by bgamari** [comment]
It may be worthwhile to introduce a `Control.Distributed.Process.Internal.Compat` module to expose a wrapper `mkWeak` to keep the CPP-nastyness isolated in one place. Let me know if you'd prefer this.

**Comment by mboes** [comment]
Looks (nearly) fine as-is IMHO. This patch could do with less code duplication: couldn't you duplicate only the LHS and not the RHS (which includes a number of gnarly lexemes and identifiers that may well diverge over time)?

**Comment by facundominguez** [comment]
LGTM

**Comment by facundominguez** [comment]
Also, thanks for the patch!

**Comment by bgamari** [comment]
@mboes, BTW, the patch has been updated.

**Pull request merged**
